### ISSUE TITLE
tree_node.hpp:85:24: error: call of overloaded

### ISSUE THREAD

**Issue by xiaolaba** [kartorz/AlphaDict#3]
hi,

forked and links as [https://github.com/xiaolaba/AlphaDict](https://github.com/xiaolaba/AlphaDict)
we used ubuntu 20.04 to comply the code, make and produced error is showing as following, any idea of what or possible a bug ?

/AlphaDict/src/lib/kary_tree/tree_node.hpp:85:24: error: call of overloaded 'next(std::__cxx11::list<ktree::tree_node<aldict_charindex>*, std::allocator<ktree::tree_node<aldict_charindex>*> >::iterator, int&)' is ambiguous
   85 |             iter = next(_children.begin(), pos);
      |                    ~~~~^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by kartorz** [comment]
It is a boost version issue, has fixed.
-#ifdef _LINUX
+#if defined(_LINUX) && BOOST_VERSION  < 105000

-    #ifdef WIN32
+   #if defined WIN32 || BOOST_VERSION  >= 105000

**Comment by kartorz** [comment]
Please update code, and try again.

**Comment by xiaolaba** [comment]
> Please update code, and try again.

thx, i just read your post, will try again later on.

**Comment by xiaolaba** [comment]
thx for the excellent masterpiece. it is work. 
I had read the test the log here,
https://github.com/xiaolaba/AlphaDict/tree/master/WSL_UBUNTU
